// Generated by gencpp from file dobot/CartesianQuat.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_CARTESIANQUAT_H
#define DOBOT_MESSAGE_CARTESIANQUAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct CartesianQuat_
{
  typedef CartesianQuat_<ContainerAllocator> Type;

  CartesianQuat_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  CartesianQuat_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::dobot::CartesianQuat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::CartesianQuat_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianQuat_

typedef ::dobot::CartesianQuat_<std::allocator<void> > CartesianQuat;

typedef boost::shared_ptr< ::dobot::CartesianQuat > CartesianQuatPtr;
typedef boost::shared_ptr< ::dobot::CartesianQuat const> CartesianQuatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::CartesianQuat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::CartesianQuat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::CartesianQuat_<ContainerAllocator1> & lhs, const ::dobot::CartesianQuat_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::CartesianQuat_<ContainerAllocator1> & lhs, const ::dobot::CartesianQuat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::CartesianQuat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::CartesianQuat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::CartesianQuat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::CartesianQuat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::CartesianQuat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::CartesianQuat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::CartesianQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a70de85a9dd451c31fa86cab10a939";
  }

  static const char* value(const ::dobot::CartesianQuat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a70de85a9dd451ULL;
  static const uint64_t static_value2 = 0xc31fa86cab10a939ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::CartesianQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/CartesianQuat";
  }

  static const char* value(const ::dobot::CartesianQuat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::CartesianQuat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 w\n"
;
  }

  static const char* value(const ::dobot::CartesianQuat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::CartesianQuat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianQuat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::CartesianQuat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::CartesianQuat_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_CARTESIANQUAT_H
